### ISSUE TITLE
Fails on initialization with Go 1.5.1

### ISSUE THREAD

**Issue by robbles** [knq/xo#1]
Running `xo` and/or any of the examples yields the following traceback:

```
panic: template: postgres.idx.go.tpl:16: illegal number syntax: "-"

goroutine 1 [running]:
text/template.Must(0x0, 0x688028, 0xc82016e220, 0x0)
	/usr/local/Cellar/go/1.5.1/libexec/src/text/template/helper.go:23 +0x4b
github.com/knq/xo/templates.init.1()
	/go/src/github.com/knq/xo/templates/templates.go:253 +0x36c
github.com/knq/xo/templates.init()
	/go/src/github.com/knq/xo/templates/types.go:72 +0x112a
github.com/knq/xo/loaders.init()
	/go/src/github.com/knq/xo/loaders/postgres.go:720 +0x79
main.init()
	/go/src/github.com/knq/xo/xo.go:271 +0x7e

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
	/usr/local/Cellar/go/1.5.1/libexec/src/runtime/asm_amd64.s:1696 +0x1
```

Is this dependent on new text/template features in Go 1.6?

**Comment by kenshaw** [comment]
Yes, this is due to the new template syntax in Go 1.6. It is very low priority to fix this, as I instead plan on rolling out pre-built packages for Linux, OSX, and Windows. The actual code generated should compile fine in Go 1.3+, as such I would suggest as a temporary work around to compile this version with Go1.6 (which should have its first release in the next week or so) and then use that for now.

**Comment by robbles** [comment]
Thanks for the quick explanation! I'll give 1.6 a try then.
