### ISSUE TITLE
Duplicate Record

### ISSUE THREAD

**Issue by saeidakbari** [knq/xo#136]
Is there any option that check if record is already available on DB?
Assume that we don`t know what record is stored on database before and we want to add new one.
How can i check  for existence first and save after that?

**Comment by kenshaw** [comment]
You can use a custom template to do this. If you're using PostgreSQL, there is an "Upsert" method that accomplishes this. This method isn't in the default templates for the other databases, because as far as I'm aware, this isn't "simple" in the others. PostgreSQL has had this functionality since 9.5.
