### ISSUE TITLE
TitleCase names with characters that are Invalid:In:Go:Identifiers

### ISSUE THREAD

**Issue by nickcarenza** [knq/xo#18]
I have a target database with column and table table with colons and the generated types look like:

```
// Account:order represents a row from public.account:order.
type Account:order struct {
	Session:id string // session:id
	Session:type sql.NullString // session:type
	Session:brandSlug string // session:brand_slug
	Session:created sql.NullInt64 // session:created
	Event:id string // event:id
	...
}
```

One idea would be to title case the identifiers using illegal characters as word boundaries then using struct tags to indicate the column names and providing a constant for the table name:

```
const AccountOrderTable = "account:order"

type AccountOrder struct {
	SessionId string `xo:"session:id"`
	SessionType sql.NullString `xo:"session:type"`
	SessionBrandSlug string `xo:"session:brand_slug"`
	SessionCreated sql.NullInt64 `xo:"session:created"`
	EventId string `xo:"event:id"`
	...
}
```

**Comment by nickcarenza** [comment]
Additionally the generated sql will need to have identifiers appropriately quoted based on the target db.

**Comment by kenshaw** [comment]
I'm not aware of any databases that support colons in identifiers. What database are you using?

**Comment by nickcarenza** [comment]
Postgres

**Comment by kenshaw** [comment]
Sorry for the delay on getting to this issue, but been busy the last couple days. The issue is actually that PostgreSQL supports basically any character inside double quotes. The way to fix this is to provide a command line option that forces escapes / normalization of characters (ie, removal) in Go identifiers, and then also in the SQL for the generated Go code to also escape the SQL identifiers. I will fix this, but I don't think I have time today to get this done. A PR would be greatly appreciated, if you can write it!

**Comment by kenshaw** [comment]
I have cleaned up the code to fix this issue. However, please note that on the command line you will need to toggle escaping (it is not enabled by default). You can simply enable `--escape-all` or `-X`:
```sh
xo -o models -X pgsql://user:pass@host/dbname
```

**Comment by nickcarenza** [comment]
@kenshaw Much appreciated!
