### ISSUE TITLE
Database generated "Created" and "LastModified" column Values

### ISSUE THREAD

**Issue by tmmunro** [knq/xo#2]
This library looks really promising, thanks for sharing it.

How should we should handle columns holding timestamps that are maintained within the database, e.g:

CREATE OR REPLACE FUNCTION "Update_Modified_Column"() RETURNS TRIGGER AS '
  BEGIN
    NEW."Modified" = NOW();
    RETURN NEW;
  END;
' LANGUAGE 'plpgsql'

CREATE TABLE "MyTable" (
    "ID" SERIAL PRIMARY KEY NOT NULL,
    "SomeText" TEXT,
    "Created" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "Modified" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
)

CREATE TRIGGER "TR_MyTable_Update_Modified_Column" BEFORE UPDATE 
    ON "MyTable" FOR EACH ROW EXECUTE PROCEDURE
    "Update_Modified_Column"()

In this case, I would prefer that the code generated by xo never inserted/update values in columns "Modified" or "Created". E.g. something like this would work:
--never-update "Modified","Created"

**Comment by kenshaw** [comment]
Yes, I'm aware of this, as we also make extensive use of timestamps being handled by the database. I had cranked out the original version of xo to replace an internal tool that was written in PHP (with Twig templates) that was generating Oracle query code for Go (this is because it was originally for a PHP project that was moved over to Go). 

I am in the midst of a massive overhaul that will provide support for MySQL, SQLite and Oracle, which should be ready relatively soon (in the next day or two). As part of this wide overhaul, I intend to add an 'ignore' parameter (or something along those lines) that will provide a simple list of fields that can be ignored completely.

However, at the end of the day, there is no way that xo can be a tool that supports all variants of all schemas in all databases and how they are used in all organizations. As such, the latest overhaul supports supplying a user-supplied template directory. Part of the flow, I imagine, is that in a specific project a user would copy the default templates provided for their database, and then put that into their own project directory and customize the templates as they see fit.

While xo could 'recognize' certain fields / names, I really feel that starts to become too much 'magic' and is really better suited by tailoring the templates for your own project.

As a temporary measure, you could modify the templates and compile your own version. The big overhaul supporting MySQL, SQLite and Oracle already supports user-supplied template directories, and it is really only a day or two away from completion.

**Comment by tmmunro** [comment]
That approach sounds absolutely fine to me, thanks a lot!
