### ISSUE TITLE
Table fields with names that match methods

### ISSUE THREAD

**Issue by THUNDERGROOVE** [knq/xo#20]
In the event that fields match methods the generator should prefix struct fields with Is or something similar.

**Comment by kenshaw** [comment]
Can you give a specific example of this? All of the generated `func`s currently do not typically hit a shared field name, as the names of generated `func`s are supposed to be verbs. IE, `AuthorByID`. If there is a problem with the foreign key relationships, then there are 3 different modes that can be forced: parent, field, key:
```sh
xo -o models --fk-mode=field pgsql://localhost/mydatabase
```

**Comment by THUNDERGROOVE** [comment]
Specifically if a table has a field "deleted"

**Comment by kenshaw** [comment]
Because xo cannot accommodate every schema design decision, you can take the base templates and create a naming strategy for deleted, etc. that makes sense for your schema. That is typically done something like the following:
```sh
# copy templates
cp -R $GOPATH/src/github.com/knq/xo/templates/postgres.*.tpl /path/to/templates

<edit templates>

# generate xo models
xo -o models --template-path=/path/to/templates pgsql://user:pass@localhost/dbname
```

Specifically for changing the way the `_deleted` meta field is managed, you only need to modify the `postgres.type.go.tpl` template. It is fairly straightforward what needs to be changed in the template for it to work with your schema design.
