### ISSUE TITLE
Question: many-to-many and link table support

### ISSUE THREAD

**Issue by erlgry** [knq/xo#30]
Hello There,

Fantastic tool. Thank you so much for your effort. This is exactly what I needed.

I looked around, however could not find any further information on many-to-many and link table support. I was wondering if there is an early version I could play around with? This along with Postgres JSON support and an input query file for query generation are few of my biggest needs. Would deeply appreciate any guidance on when these may drop.

Thanks

**Comment by kenshaw** [comment]
I have working templates for many-many/many-to-one/one-to-many relationships, but the issue is that they are very heavily customized for a private project, and we have no intention of releasing them (they contain sensitive implementation information that cannot be released). That said, it is not difficult to create your own m/m, 1-to-m, or m-to-1 templates and use them with the tool via the `--template-path` CLI option.

With regards to JSON support, I have not finished writing and testing a generic JSON type that work with the `lib/pq` driver. That said, since JSON is recognized by xo as a "custom type", all you need to do is specify the `--custom-type-package` (or `-C`) option to use a package that has a type named `JSON` in it. That type needs to be able to be serialized (and unserialized) to the database by supporting the `driver.Valuer` interface and the `sql.Scanner` interface. There's a ton of documentation available online (search on Google) on writing those interfaces for Go. You can also look at the `StringSlice` type in the xo templates as an example of an existing `sql.Scanner`/`driver.Valuer` implementation.

For reference, this is how you pass the name of a custom type package:
```sh
xo -o models -C mytypepkg pgsql://user:pass@localhost/dbname
```
(note: `goimports` processes the Go files generated by xo, which is why this will is able to work, assuming the `mytypepkg` can be found by `goimports`)

FWIW, the reason I haven't yet written a generic `JSON` type for inclusion with xo is because only MySQL and PostgreSQL support JSON out of the box (as far as I know). Additionally, we don't use JSON types in our schemas. It would be fairly easy to write one, however -- and if you do, please send a pull request and I'll merge it (assuming it is written/works well)!

**Comment by erlgry** [comment]
@kenshaw thanks. I will give both of these a try. 

It looks like JSON support should be quite straightforward for me to implement

Could you provide some guidance on what do you typically generate when there are m/m relations and link table? E.g. For tables "product", "collection", "product_collection", what additional types (and methods upon types) do you generate? If there is any skeleton code you can share, I can take it rest of the way

**Comment by codepushr** [comment]
I'd also be interested in a little more insight!

**Comment by codepushr** [comment]
I'd also be interested in a little more insight! I would like to create aggregated fields. Example: 
User <-> UserAddress <-> Address

And now create a "Addresses" field for User and a "Users" field for Address... Where do I start?
