### ISSUE TITLE
sqlite3 generator does not handle table constraints

### ISSUE THREAD

**Issue by neitzj** [knq/xo#42]
Here is my test schema

CREATE TABLE user (
    user_id     TEXT NON NULL PRIMARY KEY,
    email       TEXT,
    first_name  TEXT,
    last_name   TEXT,
    headline    TEXT,
    profile_url TEXT,
    location    TEXT,
    username    TEXT,
    password     TEXT
);

CREATE TABLE id_provider
(
    provider_id TEXT NOT NULL,
    user_id     TEXT NOT NULL REFERENCES user( user_id ),
    network     TEXT,

```
PRIMARY KEY( provider_id, user_id )
```

);

If I remove the PRIMARY KEY table constraint it generates fine. With it the following error is generated

error: sql: Scan error on column index 5: sql/driver: couldn't convert 2 into type bool

Would it be possible to support composite primary keys? I need them for the project I'm working on and would like to use xo to save me some time. If not is there some sort of work around where I can still generate most of code using xo. 

Regards and thanks for making this work public.

**Comment by kenshaw** [comment]
This can definitely be fixed, but I'm not likely to be able to fix this today. The issue is that I wasn't aware that SQLite supported this for primary keys. I need to rewrite quite a bit of the way this is queried for SQLite. Unfortunately, SQLite works uses `PRAGMA` statements for introspection, which is completely different from all the other supported databases (all of the other databases use tables/views for SQL introspection). It's not too difficult to fix, but requires some time investment.

**Comment by kenshaw** [comment]
BTW -- you have a spelling mistake in your schema: `user_id TEXT NON NULL PRIMARY KEY,` should be `user_id TEXT NOT NULL PRIMARY KEY,`

**Comment by neitzj** [comment]
Thanks for the quick response! And pointing out the error!

I'll keep checking back once you have sometime to take a look.

Thanks again.

**Comment by kenshaw** [comment]
Please see #58.
