### ISSUE TITLE
Blocking empty string values when columns are null?

### ISSUE THREAD

**Issue by Xeoncross** [knq/xo#54]
Go defines the zero value for strings to be an empty string, so there is no way to test if the value has been set to empty, or was simply empty from the beginning without tracking each set on the struct properties.

How should we handle columns that do not allow null values, but should also not allow *empty* values for structs that have strings as the column type?

```
type Person struct {
	ID     int64           `json:"id"`     // id
	Name string          `json:"name"` // name
	_exists, _deleted bool
}

...
	p = models.Person{}
	err = p.Save(db) // <-- Should not have worked since struct is empty and person.name does not allow null values

	if err != nil {
		fmt.Println(err)
	}
	fmt.Println("Person.ID, p.ID) 
```

I can manually edit all the models but surely more people need `"" == nil` in this case than not.
See also [sql.NullString](https://golang.org/pkg/database/sql/#NullString).

**Comment by kenshaw** [comment]
xo should detect nullable strings, and use the `sql.NullString` type accordingly. If it's not working for a specific database, then I need to know the database, and get at least a minimal version of the schema that was used with that database. Because all the various databases support many different synonyms for `varchar` type fields, the respective database loader (in the `loaders/` directory) may not correctly recognize it.

**Comment by kenshaw** [comment]
Closing issue due to no response with database information.
