### ISSUE TITLE
errors generating schema_migration model

### ISSUE THREAD

**Issue by willie** [knq/xo#7]
This is an easy one to report and, well, one that I can ignore pretty easily, but will impede Rails projects wanting to us xo. All Rails projects have a schema_migration table. Here's the MySQL description:

```
mysql> describe schema_migrations;
+---------+--------------+------+-----+---------+-------+
| Field   | Type         | Null | Key | Default | Extra |
+---------+--------------+------+-----+---------+-------+
| version | varchar(255) | NO   | PRI | NULL    |       |
+---------+--------------+------+-----+---------+-------+
1 row in set (0.01 sec)

mysql> show index from schema_migrations;
+-------------------+------------+--------------------------+--------------+-------------+-----------+-------------+----------+--------+------+------------+---------+---------------+
| Table             | Non_unique | Key_name                 | Seq_in_index | Column_name | Collation | Cardinality | Sub_part | Packed | Null | Index_type | Comment | Index_comment |
+-------------------+------------+--------------------------+--------------+-------------+-----------+-------------+----------+--------+------+------------+---------+---------------+
| schema_migrations |          0 | unique_schema_migrations |            1 | version     | A         |         661 |     NULL | NULL   |      | BTREE      |         |               |
+-------------------+------------+--------------------------+--------------+-------------+-----------+-------------+----------+--------+------+------------+---------+---------------+
1 row in set (0.00 sec)
```

And here is the error go fmt gives on the output:

```
$ go fmt schemamigration.xo.go 
schemamigration.xo.go:93:16: expected operand, found ','
schemamigration.xo.go:95:2: missing ',' in argument list
schemamigration.xo.go:96:1: expected operand, found '}'
schemamigration.xo.go:100:2: missing ',' in argument list
schemamigration.xo.go:101:3: expected operand, found 'return'
schemamigration.xo.go:102:2: expected operand, found '}'
schemamigration.xo.go:104:2: missing ',' in argument list
schemamigration.xo.go:105:1: expected operand, found '}'
schemamigration.xo.go:109:2: missing ',' in argument list
schemamigration.xo.go:112:2: missing ',' in argument list
schemamigration.xo.go:113:3: expected operand, found 'return'
```

[schemamigration.xo.go.zip](https://github.com/knq/xo/files/150357/schemamigration.xo.go.zip)

**Comment by kenshaw** [comment]
Oh -- interesting -- yeah, typically schema migration tables do a pretty bad design in general by having only one field as a unique key, which is the cause of the problem here, as the current templates assume the primary key is being managed by the database.

Don't get me started on why this is a horrible design for a table!

The answer here, I think, is to finish the include/exclude options that I have been working off, but have delayed finishing in the interest of getting the databases all to a minimum feature set.

xo is fairly dumb/naive, and these kinds of cases will show that. It's definitely in the interest though that it be smarter about such conditions. I just need to think a bit about how I want to support this out of the box.

**Comment by willie** [comment]
Include/exclude sounds like a good option. Thanks again for the neat code gen.

**Comment by kenshaw** [comment]
I created a temporary workaround for this, but will likely revisit the logic added in this commit at a later date.

xo should now work, "as expected" for tables with only one field that is the primary key.

**Comment by willie** [comment]
Confirmed. Thanks!
