### ISSUE TITLE
Single Field Tables Fail

### ISSUE THREAD

**Issue by robmuh** [knq/xo#96]
I know this is nitpicking because it makes no sense to have a table with nothing in it but a primary key, but I ran into this odd bug during some testing:

![screen shot 2017-04-09 at 10 53 48 am](https://cloud.githubusercontent.com/assets/3749067/24838270/dc16fb58-1d12-11e7-89c3-8a1d6f2feaeb.png)

![screen shot 2017-04-09 at 10 51 17 am](https://cloud.githubusercontent.com/assets/3749067/24838253/935f9a8c-1d12-11e7-84b9-15eeb9b7fd1e.png)

![screen_shot_2017-04-09_at_10_51_06_am](https://cloud.githubusercontent.com/assets/3749067/24838254/950e6656-1d12-11e7-91f9-dd98920f83e9.png)

Obviously the workaround is to make sure one includes at least one meaningful field besides the primary key or any that are being ignored. I don't know if this could even be considered a bug other than the fact that it is conceivable to have tables with nothing but primary keys that link together others.

Thanks again for this great tool.

**Comment by turnkey-commerce** [comment]
Thanks for the report on this.  Usually if it's a primary and foreign key it would be unlikely to require an update.  We did make some changes lately to allow it to be inserted properly if it's not an auto-incremented key. 

This one might be hard to solve since the c.Handle that is passed would be both the lookup and the updated field so it would be a noop or error in the WHERE clause.  Maybe in these cases we should omit the Update method altogether?

**Comment by robmuh** [comment]
Yeah, that would probably be the easiest. That way at least the code will
compile.

*Rob Muhlestein*
@SkilStak <http://twitter.com/skilstak>, Inc.
rob@skilstak.com
704-310-6778
@robmuh <http://twitter.com/robmuh>

**Comment by kenshaw** [comment]
This is not difficult to fix, but it does beg the question what would be the purpose of fixing this? Fixing this in the base templates would end up cluttering up the templates pretty badly, especially since the Go template syntax is not the most elegant thing in the world. Is there an absolute requirement to fix this? In many ways, this exposes a problem/mistake that the database developer has made...

I haven't tried it, but can you even do a `SELECT *` against a table with NO FIELDS? Or can you do a `SELECT` without specifying a single field? Additionally, will the various databases even "parse" UPDATE TABLE as correct? Because there's no "select clause" in the update statement.

**Comment by kenshaw** [comment]
I just tried this in PostgreSQL -- you can have an empty field list in the `SELECT`, but there is NO way that I can see to craft an `UPDATE` statement that is valid with a table that has no fields:

```
booktest=> create table t;
ERROR:  syntax error at or near ";"
LINE 1: create table t;
                      ^
booktest=> create table t();
CREATE TABLE
booktest=> select * from t;
--
(0 rows)

booktest=> select from t;
--
(0 rows)

booktest=> update t;
ERROR:  syntax error at or near ";"
LINE 1: update t;
                ^
booktest=> update t set;
ERROR:  syntax error at or near ";"
LINE 1: update t set;
                    ^
booktest=> update t set();
ERROR:  syntax error at or near ")"
LINE 1: update t set();
                     ^
booktest=> 
```

**Comment by kenshaw** [comment]
For the record, I'm willing to fix this, but I literally don't know how this even makes sense. What's the point of generating code with `xo` that generates a single empty struct that has no fields, no retrieval methods, and no update/delete methods?

**Comment by robmuh** [comment]
While it is definitely extremely rare, I could see a use case for a table
with nothing but a single primary key (in fact I have one). However, an
update to such a table row seems impossible. For example, with delete
cascade this could be used to remove all other linked entities. Since the
work-around for xo is to simply add ANY other field I can make that work. I
personally consider it a bug that there is any case in which xo creates
code that prevents my application from compiling. I tend to agree with the
notion of not including the Update code in such an (edge) case, but I am
equally ok with it being an acceptable behavior with a caveat raising the
issue somewhere for folks to see.

*Rob Muhlestein*
@SkilStak <http://twitter.com/skilstak>, Inc.
rob@skilstak.com
704-310-6778
@robmuh <http://twitter.com/robmuh>

**Comment by turnkey-commerce** [comment]
I can take a look at this.  There is a related problem in a more common scenario where we only have two primary keys in a table that is not autoincrement (e.g. many-to-many link table). In those cases it doesn't make sense to do updates on the table either. For that we will also need to support multiple PK's and can solve both of these issues.

**Comment by robmuh** [comment]
Thanks guys.

**Comment by turnkey-commerce** [comment]
You're welcome.
